project:
  type: website

execute:
  freeze: true

website:
  title: "Nomuulin Namdag"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume/Profile.pdf
        text: About
      - writings.qmd

format:
  html:
    theme: 
      light: quartz
      dark: vapor
    css: styles.css
    toc: true
    page-layout: full

body-header: | 
  ![Header image](/header.jpeg)
